-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 13:09:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8mb3 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`user` ;

CREATE TABLE IF NOT EXISTS `project`.`user` (
  `userid` VARCHAR(45) NOT NULL,
  `userpwd` VARCHAR(45) NOT NULL,
  `useremail` VARCHAR(100) NULL DEFAULT NULL,
  `userclass` INT NULL DEFAULT NULL,
  `joindate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `project`.`houseinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`houseinfo` ;

CREATE TABLE IF NOT EXISTS `project`.`houseinfo` (
  `aptCode` INT NOT NULL,
  `aptName` VARCHAR(50) NULL DEFAULT NULL,
  `dongCode` VARCHAR(10) NULL DEFAULT NULL,
  `dongName` VARCHAR(30) NULL DEFAULT NULL,
  `buildYear` INT NULL DEFAULT NULL,
  `jibun` VARCHAR(30) NULL DEFAULT NULL,
  `lat` VARCHAR(30) NULL DEFAULT NULL,
  `lng` VARCHAR(30) NULL DEFAULT NULL,
  `img` VARCHAR(50) NULL DEFAULT NULL,
  `userid` VARCHAR(45) NULL,
  PRIMARY KEY (`aptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `project`.`bookmark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`bookmark` ;

CREATE TABLE IF NOT EXISTS `project`.`bookmark` (
  `userid` VARCHAR(45) NOT NULL,
  `aptCode` INT NOT NULL,
  INDEX `fk_bookmark_user1_idx` (`userid` ASC) VISIBLE,
  INDEX `fk_bookmark_houseinfo1_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `fk_bookmark_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `project`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookmark_houseinfo1`
    FOREIGN KEY (`aptCode`)
    REFERENCES `project`.`houseinfo` (`aptCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `project`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`comment` ;

CREATE TABLE IF NOT EXISTS `project`.`comment` (
  `cmno` INT NOT NULL,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `star` DOUBLE NULL DEFAULT NULL,
  `userid` VARCHAR(45) NOT NULL,
  `aptCode` INT NOT NULL,
  PRIMARY KEY (`cmno`),
  INDEX `fk_comment_user1_idx` (`userid` ASC) VISIBLE,
  INDEX `fk_comment_houseinfo1_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `project`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_houseinfo1`
    FOREIGN KEY (`aptCode`)
    REFERENCES `project`.`houseinfo` (`aptCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
